import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend, Lexend_Giga } from "next/font/google";
import Navbar from "@/components/Navbar";
import PageAnimator from "@/components/PageAnimator";
import "./globals.css";
import "@/styles/pageAnimations.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const lexendGiga = Lexend_Giga({
  variable: "--font-lexend-giga",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexend.variable} ${lexendGiga.variable} antialiased`}
      >
        <Navbar />
        <PageAnimator>
          {children}
        </PageAnimator>
      </body>
    </html>
  );
}
